server:
  port: 8016

spring:
  application:
    name: test-16-redis
  main:
    allow-bean-definition-overriding: true # 意思是后来发现的bean会覆盖之前相同名称的bean
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  redis:
    cluster:
      # 集群节点
      nodes: 192.168.10.11:7001,192.168.10.11:7002,192.168.10.12:7001,192.168.10.12:7002,192.168.10.13:7001,192.168.10.13:7002
      # 最大重定向次数
      max-redirects: 5
    password: admin
    lettuce:
      shutdown-timeout: 0
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
        enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.test.redis.mapper
  configuration: #配置此种打印方式会在控制台打印出sql和参数，及sql执行的所有结果集
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl