server:
  port: 8012

spring:
  application:
    name: test-12-rabbitmq-consumer-01
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    # 取消工作队列模式的预取机制（多个消费者轮询获取消息）
#    listener:
#      simple:
#        prefetch: 1 # 每次只能获取一条，处理完成才能获取下一条
#        acknowledge-mode: manual  # 设置消费者端手动 ack 确认
#        retry:
#          enabled: true # 是否支持重试
  rabbitmq:
#    addresses: 10.21.36.11:5672,10.21.36.12:5672,10.21.36.13:5672
    addresses: 10.21.36.126:5672
    username: spadger
    password: spadger
    virtual-host: /